import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import {} from '../components/Atoms/AtomsImport';
import {} from '../components/Molecules/MoleculesImport';
import {} from '../components/Organisms/OrganismsImport';
import { SidebarLayout } from '../components/Templates/TemplatesImport';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SidebarLayout mainContent={'hello'} />
    </div>
  );
};

export default Home;
