import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { PhoneIcon, AddIcon, WarningIcon } from '@chakra-ui/icons';
import { ListItem } from '../components/Atoms/ListItems/ListItem';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ListItem Icon={<WarningIcon w={6} h={6} mr={3} />} name="world2" />
        <ListItem Icon={<AddIcon w={6} h={6} mr={3} />} name="world2" />
        <ListItem />
      </div>
    </div>
  );
};

export default Home;
