// require('chromedriver');
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('hello world', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('hello world', async function() {
    await driver.get("https://www.google.com/")
    await driver.manage().window().setRect({ width: 1283, height: 906 })
    await driver.findElement(By.name("q")).sendKeys("hello word")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("div:nth-child(3) > .tF2Cxc .LC20lb")).click()
  })
})
