version: '3'
services:
  web:
    image: node
    ports:
      - '3333:8080'
    volumes:
      - ./:/home/
  db:
    image: mysql
    ports:
      - '4444:3306'
    volumes:
      - './DBdata/:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'sawada'
      MYSQL_DATABASE: 'selenium_demo'
      MYSQL_USER: 'sawada'
      MYSQL_PASSWORD: 'sawada'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'